.code
extern lpOrigProcs:QWORD
agsDeInit proc
    jmp lpOrigProcs[0]
agsDeInit endp
agsDriverExtensionsDX11_BeginUAVOverlap proc
    jmp lpOrigProcs[8]
agsDriverExtensionsDX11_BeginUAVOverlap endp
agsDriverExtensionsDX11_CreateBuffer proc
    jmp lpOrigProcs[16]
agsDriverExtensionsDX11_CreateBuffer endp
agsDriverExtensionsDX11_CreateDevice proc
    jmp lpOrigProcs[24]
agsDriverExtensionsDX11_CreateDevice endp
agsDriverExtensionsDX11_CreateFromDevice proc
    jmp lpOrigProcs[32]
agsDriverExtensionsDX11_CreateFromDevice endp
agsDriverExtensionsDX11_CreateTexture1D proc
    jmp lpOrigProcs[40]
agsDriverExtensionsDX11_CreateTexture1D endp
agsDriverExtensionsDX11_CreateTexture2D proc
    jmp lpOrigProcs[48]
agsDriverExtensionsDX11_CreateTexture2D endp
agsDriverExtensionsDX11_CreateTexture3D proc
    jmp lpOrigProcs[56]
agsDriverExtensionsDX11_CreateTexture3D endp
agsDriverExtensionsDX11_Destroy proc
    jmp lpOrigProcs[64]
agsDriverExtensionsDX11_Destroy endp
agsDriverExtensionsDX11_DestroyDevice proc
    jmp lpOrigProcs[72]
agsDriverExtensionsDX11_DestroyDevice endp
agsDriverExtensionsDX11_EndUAVOverlap proc
    jmp lpOrigProcs[80]
agsDriverExtensionsDX11_EndUAVOverlap endp
agsDriverExtensionsDX11_GetMaxClipRects proc
    jmp lpOrigProcs[88]
agsDriverExtensionsDX11_GetMaxClipRects endp
agsDriverExtensionsDX11_IASetPrimitiveTopology proc
    jmp lpOrigProcs[96]
agsDriverExtensionsDX11_IASetPrimitiveTopology endp
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect proc
    jmp lpOrigProcs[104]
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect endp
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect proc
    jmp lpOrigProcs[112]
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect endp
agsDriverExtensionsDX11_MultiDrawInstancedIndirect proc
    jmp lpOrigProcs[120]
agsDriverExtensionsDX11_MultiDrawInstancedIndirect endp
agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect proc
    jmp lpOrigProcs[128]
agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect endp
agsDriverExtensionsDX11_NotifyResourceBeginAllAccess proc
    jmp lpOrigProcs[136]
agsDriverExtensionsDX11_NotifyResourceBeginAllAccess endp
agsDriverExtensionsDX11_NotifyResourceEndAllAccess proc
    jmp lpOrigProcs[144]
agsDriverExtensionsDX11_NotifyResourceEndAllAccess endp
agsDriverExtensionsDX11_NotifyResourceEndWrites proc
    jmp lpOrigProcs[152]
agsDriverExtensionsDX11_NotifyResourceEndWrites endp
agsDriverExtensionsDX11_NumPendingAsyncCompileJobs proc
    jmp lpOrigProcs[160]
agsDriverExtensionsDX11_NumPendingAsyncCompileJobs endp
agsDriverExtensionsDX11_SetClipRects proc
    jmp lpOrigProcs[168]
agsDriverExtensionsDX11_SetClipRects endp
agsDriverExtensionsDX11_SetDepthBounds proc
    jmp lpOrigProcs[176]
agsDriverExtensionsDX11_SetDepthBounds endp
agsDriverExtensionsDX11_SetDiskShaderCacheEnabled proc
    jmp lpOrigProcs[184]
agsDriverExtensionsDX11_SetDiskShaderCacheEnabled endp
agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount proc
    jmp lpOrigProcs[192]
agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount endp
agsDriverExtensionsDX11_SetViewBroadcastMasks proc
    jmp lpOrigProcs[200]
agsDriverExtensionsDX11_SetViewBroadcastMasks endp
agsDriverExtensionsDX11_WriteBreadcrumb proc
    jmp lpOrigProcs[208]
agsDriverExtensionsDX11_WriteBreadcrumb endp
agsDriverExtensionsDX12_CreateDevice proc
    jmp lpOrigProcs[216]
agsDriverExtensionsDX12_CreateDevice endp
agsDriverExtensionsDX12_CreateFromDevice proc
    jmp lpOrigProcs[224]
agsDriverExtensionsDX12_CreateFromDevice endp
agsDriverExtensionsDX12_Destroy proc
    jmp lpOrigProcs[232]
agsDriverExtensionsDX12_Destroy endp
agsDriverExtensionsDX12_DestroyDevice proc
    jmp lpOrigProcs[240]
agsDriverExtensionsDX12_DestroyDevice endp
agsDriverExtensionsDX12_PopMarker proc
    jmp lpOrigProcs[248]
agsDriverExtensionsDX12_PopMarker endp
agsDriverExtensionsDX12_PushMarker proc
    jmp lpOrigProcs[256]
agsDriverExtensionsDX12_PushMarker endp
agsDriverExtensionsDX12_SetMarker proc
    jmp lpOrigProcs[264]
agsDriverExtensionsDX12_SetMarker endp
agsInit proc
    jmp lpOrigProcs[272]
agsInit endp
agsSetDisplayMode proc
    jmp lpOrigProcs[280]
agsSetDisplayMode endp
end
